### ISSUE TITLE
XenonRecomp: terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by mdmrk** [hedge-dev/XenonRecomp#150]
I'm having trouble running `XenonRecomp` - it crashes with a memory allocation error after running for a very long time. I'm trying to decompile GTA IV (USA). Should this process normally take 26+ minutes?

```sh
$ time ../XenonRecomp/build/XenonRecomp/XenonRecomp lib/config/SWA.toml ../XenonRecomp/XenonUtils/ppc_context.h
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

________________________________________________________
Executed in   26.00 mins    fish           external
   usr time   24.01 mins    0.61 millis   24.01 mins
   sys time    1.25 mins    1.77 millis    1.25 mins

fish: Job 1, 'time ../XenonRecomp/build/Xenon…' terminated by signal SIGABRT (Abort)
```

I captured a segment of the execution process and got this:

![Image](https://github.com/user-attachments/assets/345c965b-5bd4-4cd6-baae-5165dc349cbf)

Looks like it takes a long time decrypting the .xex file.

The config file used looks like this:

Also I run `XenonAnalyse` successfully, it outputs a +10k loc file so that part seems to work correctly.

`SWA.toml`
```toml
[main]
file_path = "../../default.xex"
patched_file_path = "../private/default_patched.xex"
out_directory_path = "../ppc"
switch_table_file_path = "SWA_switch_tables.toml"

skip_lr = true
skip_msr = true
ctr_as_local = true
xer_as_local = true
reserved_as_local = true
cr_as_local = true
non_argument_as_local = true
non_volatile_as_local = true

restgprlr_14_address = 0x8298eb30
savegprlr_14_address = 0x8298eae0
restfpr_14_address = 0x8299015c
savefpr_14_address = 0x82990110
restvmx_14_address = 0x82990598
savevmx_14_address = 0x82990300
restvmx_64_address = 0x8299062c
savevmx_64_address = 0x82990394
```

After crash and +26 minutes running, the `../ppc` folder remains empty
