### ISSUE TITLE
Analyzer does not output toml

### ISSUE THREAD

**Issue by Permdog99** [hedge-dev/XenonRecomp#6]
I tried to use the XenonAnalyze.exe to output Minecraft: Xbox 360 Edition's jump tables to a toml, but it does not seem to create any toml in the path I specified. Nothing shows up in the terminal either

**Comment by Permdog99** [comment]
Looking to start a static recomp project of Minecraft so any help would be nice

**Comment by Permdog99** [comment]
Okay new development: now it won't build.

![Image](https://github.com/user-attachments/assets/783fc6c5-8dc1-4f74-b205-8421507165fd)

**Comment by Permdog99** [comment]
Right so apparently I was building in Release rather than Debug, and also not specifying a toml output. Now it creates the toml, but doesn't actually get the jump tables

![Image](https://github.com/user-attachments/assets/fc5664d0-fb76-481f-8b0c-0532ec19cc2f)

**Comment by blueskythlikesclouds** [comment]
Sorry, the release of UnleashedRecomp has been a bit chaotic so I might not be able to give help immediately.
Like I say in the README, the patterns of the jump tables might differ between games, so it's possible the existing pattern checks don't match what this game has. 

The patterns expected in Sonic Unleashed are here: https://github.com/hedge-dev/XenonRecomp/blob/main/XenonAnalyse/main.cpp#L253

See if you can find anything similar. It's also possible the pattern is part of the optimization process in newer Xbox 360 versions which would unfortunately heavily complicaet this.

**Comment by AleBello7276** [comment]
> Sorry, the release of UnleashedRecomp has been a bit chaotic so I might not be able to give help immediately. Like I say in the README, the patterns of the jump tables might differ between games, so it's possible the existing pattern checks don't match what this game has.
> 
> The patterns expected in Sonic Unleashed are here: https://github.com/hedge-dev/XenonRecomp/blob/main/XenonAnalyse/main.cpp#L253
> 
> See if you can find anything similar. It's also possible the pattern is part of the optimization process in newer Xbox 360 compiler versions which would unfortunately heavily complicate this.


i see, i'm finding some differences like for example the "computedSwitch" in Minecraft is:

![Image](https://github.com/user-attachments/assets/7b0c81ed-2e2f-4451-b0c6-1ad58b970447)

**Comment by Sakimotor** [comment]
> Sorry, the release of UnleashedRecomp has been a bit chaotic so I might not be able to give help immediately. Like I say in the README, the patterns of the jump tables might differ between games, so it's possible the existing pattern checks don't match what this game has.
> 
> The patterns expected in Sonic Unleashed are here: https://github.com/hedge-dev/XenonRecomp/blob/main/XenonAnalyse/main.cpp#L253
> 
> See if you can find anything similar. It's also possible the pattern is part of the optimization process in newer Xbox 360 compiler versions which would unfortunately heavily complicate this.

Hello, I have found many such patterns inside of Tetris The Grand Master: Ace, but for some reason XenonAnalyse doesn't output any .toml after running for a little while. I tried it on other games and it did give out either empty or filled tmls, so this behaviour is quite intriguing. 

![Image](https://github.com/user-attachments/assets/2a2dbe9c-0bc2-469b-8b9d-4a4cecaaf4a5)

Also, is  XenonRecomp supposed to Decompile the game's executable even if it doesn't happen to find any jumptables ? I made a .toml file that doesn't have much information but should still give some basic information to the tool I think

```toml
[main]
file_path = "tgma.xex"
out_directory_path = "../tgma"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

restgprlr_14_address = 0x823100F0
savegprlr_14_address = 0x823100A0
restfpr_14_address = 0x8231019C
savefpr_14_address = 0x82310150
restvmx_14_address = 0x823170F8
savevmx_14_address = 0x82316E60
restvmx_64_address = 0x8231718C
savevmx_64_address = 0x82316EF4

longjmp_address = 0x823191E0
setjmp_address = 0x82319300

invalid_instructions = [
    { data = 0x00000000, size = 4 }, # Padding
    { data = 0x8233ba2c, size = 8 }  # C Specific Frame Handler 
]
```


Sorry, I'm not really looking to get all the work chewed and have a step by step tutorial brought on the table to me, but I don't think I left anything out in what was written for the README

Also, if it can help, I compiled the tool with MSYS2 CLANG64 and Ninja, as a Debug project.
