### ISSUE TITLE
XenonRecomp.exe: Debug Assertion Failed!

### ISSUE THREAD

**Issue by joao678** [hedge-dev/XenonRecomp#7]
So I managed to generate the jump table with XenonAnalyse and create a config for recomp like this, but when running XenonRecomp with said settings it gives me a "Debug Asssertion Failed!"

Clang 19.1.1 was used to build the projects

```toml
[main]
file_path = "te/default.xex"
patched_file_path = "te/default_patched.xex"
out_directory_path = "ppc"
switch_table_file_path = "switch_table.toml"
```
![Image](https://github.com/user-attachments/assets/9b070189-50f8-413c-8c9f-19d8055a12b6)
